"""
Lesson 5a — House price predictor.

A "middle ground" example between pragma_mini.py (pets, 3 keys) and the
streaming churn predictor (4 keys × 15 events). Here:

  - 10 keys per record (richer structure, closer to real PRAGMA banking events).
  - One record per house (no event sequence — simpler).
  - 5-class price prediction (bargain / cheap / average / expensive / luxury).
  - REALISTIC CORRELATIONS between attributes (beach houses tend to have
    pools, vintage houses are usually smaller, etc.) — this is what gives
    MLM something contextual to learn.

Same PRAGMA recipe applies:

  1. Tokenise each house as (key, value) pairs.
  2. Pre-train via fill-in-the-blank (MLM) — no price labels.
  3. Freeze encoder. Add a 5-way price-classifier head.
  4. Train head on a small labelled set.
  5. Compare to a baseline that doesn't pre-train.

Run:  python3 05a_house_predictor.py
"""

import random
import copy
import torch
import torch.nn as nn

torch.manual_seed(0)
random.seed(0)


# ============================================================================
# PART 1 — Synthetic house data WITH REALISTIC CORRELATIONS
# ============================================================================
# Each house is generated by first picking an ARCHETYPE (cottage, suburb,
# apartment, vintage, beach), then sampling each attribute from that
# archetype's distribution. This creates inter-attribute correlations —
# e.g., beach houses tend to have pools; downtown houses rarely have gardens.
#
# Why this matters: MLM has to learn these correlations to fill in blanks
# well. The frozen encoder ends up with rich representations the linear
# probe can leverage. WITHOUT correlations, the attributes are independent
# and MLM has nothing to learn beyond "predict any value uniformly".

KEYS = ["bedrooms", "bathrooms", "size", "age", "neighborhood",
        "garage", "pool", "garden", "schools", "condition"]

# Each archetype gives a distribution (list of weights) over the possible
# values for each key. None means "use uniform random".
ARCHETYPES = {
    # Small old cottages in the countryside
    "rural_cottage": {
        "bedrooms":     {"1bed":2, "2bed":5, "3bed":3, "4bed":1, "5+bed":0},
        "bathrooms":    {"1bath":6, "2bath":3, "3+bath":1},
        "size":         {"small":5, "medium":4, "large":1, "huge":0},
        "age":          {"new":0, "modern":1, "older":4, "vintage":5},
        "neighborhood": {"downtown":0, "suburb":1, "rural":8, "beach":1},
        "garage":       {"nogarage":3, "1car":5, "2car":2},
        "pool":         {"nopool":9, "haspool":1},
        "garden":       {"nogarden":1, "smallgarden":3, "largegarden":6},
        "schools":      {"poorschool":4, "avgschool":4, "goodschool":2, "excschool":0},
        "condition":    {"poorcond":2, "faircond":4, "goodcond":3, "exccond":1},
    },
    # Standard suburban family homes
    "suburban_family": {
        "bedrooms":     {"1bed":0, "2bed":1, "3bed":5, "4bed":3, "5+bed":1},
        "bathrooms":    {"1bath":1, "2bath":6, "3+bath":3},
        "size":         {"small":1, "medium":5, "large":3, "huge":1},
        "age":          {"new":2, "modern":5, "older":2, "vintage":1},
        "neighborhood": {"downtown":1, "suburb":7, "rural":1, "beach":1},
        "garage":       {"nogarage":1, "1car":3, "2car":6},
        "pool":         {"nopool":7, "haspool":3},
        "garden":       {"nogarden":1, "smallgarden":5, "largegarden":4},
        "schools":      {"poorschool":0, "avgschool":3, "goodschool":5, "excschool":2},
        "condition":    {"poorcond":0, "faircond":2, "goodcond":5, "exccond":3},
    },
    # Tiny urban apartments
    "urban_apartment": {
        "bedrooms":     {"1bed":4, "2bed":4, "3bed":2, "4bed":0, "5+bed":0},
        "bathrooms":    {"1bath":5, "2bath":4, "3+bath":1},
        "size":         {"small":7, "medium":2, "large":1, "huge":0},
        "age":          {"new":2, "modern":5, "older":2, "vintage":1},
        "neighborhood": {"downtown":9, "suburb":1, "rural":0, "beach":0},
        "garage":       {"nogarage":7, "1car":2, "2car":1},
        "pool":         {"nopool":9, "haspool":1},
        "garden":       {"nogarden":8, "smallgarden":2, "largegarden":0},
        "schools":      {"poorschool":1, "avgschool":3, "goodschool":4, "excschool":2},
        "condition":    {"poorcond":1, "faircond":3, "goodcond":4, "exccond":2},
    },
    # Luxury beach homes
    "luxury_beach": {
        "bedrooms":     {"1bed":0, "2bed":1, "3bed":2, "4bed":4, "5+bed":3},
        "bathrooms":    {"1bath":0, "2bath":2, "3+bath":8},
        "size":         {"small":0, "medium":1, "large":4, "huge":5},
        "age":          {"new":5, "modern":4, "older":1, "vintage":0},
        "neighborhood": {"downtown":0, "suburb":0, "rural":0, "beach":10},
        "garage":       {"nogarage":0, "1car":1, "2car":9},
        "pool":         {"nopool":1, "haspool":9},
        "garden":       {"nogarden":0, "smallgarden":2, "largegarden":8},
        "schools":      {"poorschool":0, "avgschool":1, "goodschool":3, "excschool":6},
        "condition":    {"poorcond":0, "faircond":0, "goodcond":3, "exccond":7},
    },
    # Aging downtown stock
    "old_townhouse": {
        "bedrooms":     {"1bed":1, "2bed":4, "3bed":4, "4bed":1, "5+bed":0},
        "bathrooms":    {"1bath":4, "2bath":5, "3+bath":1},
        "size":         {"small":2, "medium":5, "large":2, "huge":1},
        "age":          {"new":0, "modern":1, "older":4, "vintage":5},
        "neighborhood": {"downtown":5, "suburb":4, "rural":1, "beach":0},
        "garage":       {"nogarage":4, "1car":4, "2car":2},
        "pool":         {"nopool":9, "haspool":1},
        "garden":       {"nogarden":4, "smallgarden":5, "largegarden":1},
        "schools":      {"poorschool":2, "avgschool":4, "goodschool":3, "excschool":1},
        "condition":    {"poorcond":3, "faircond":4, "goodcond":2, "exccond":1},
    },
}

ARCHETYPE_WEIGHTS = {
    "rural_cottage":   2,
    "suburban_family": 4,
    "urban_apartment": 2,
    "luxury_beach":    1,
    "old_townhouse":   2,
}

VALUE_BUCKETS = {
    "bedrooms":     ["1bed", "2bed", "3bed", "4bed", "5+bed"],
    "bathrooms":    ["1bath", "2bath", "3+bath"],
    "size":         ["small", "medium", "large", "huge"],
    "age":          ["new", "modern", "older", "vintage"],
    "neighborhood": ["downtown", "suburb", "rural", "beach"],
    "garage":       ["nogarage", "1car", "2car"],
    "pool":         ["nopool", "haspool"],
    "garden":       ["nogarden", "smallgarden", "largegarden"],
    "schools":      ["poorschool", "avgschool", "goodschool", "excschool"],
    "condition":    ["poorcond", "faircond", "goodcond", "exccond"],
}

# Linear contribution of each value to price (in $k).
PRICE_WEIGHTS = {
    "bedrooms":     {"1bed": 0, "2bed": 30, "3bed": 60, "4bed": 90, "5+bed": 120},
    "bathrooms":    {"1bath": 0, "2bath": 25, "3+bath": 55},
    "size":         {"small": 0, "medium": 80, "large": 160, "huge": 260},
    "age":          {"new": 60, "modern": 30, "older": 0, "vintage": 20},
    "neighborhood": {"downtown": 150, "suburb": 50, "rural": 0, "beach": 200},
    "garage":       {"nogarage": 0, "1car": 20, "2car": 50},
    "pool":         {"nopool": 0, "haspool": 30},
    "garden":       {"nogarden": 0, "smallgarden": 15, "largegarden": 40},
    "schools":      {"poorschool": 0, "avgschool": 40, "goodschool": 90, "excschool": 150},
    "condition":    {"poorcond": -50, "faircond": 0, "goodcond": 50, "exccond": 110},
}
PRICE_BASE = 100  # in $k


PAD, MASK = "<pad>", "<mask>"
VALUES = [v for vs in VALUE_BUCKETS.values() for v in vs]
vocab = [PAD, MASK] + KEYS + VALUES
tok2id = {t: i for i, t in enumerate(vocab)}
V = len(vocab)

PRICE_CLASSES = ["bargain", "cheap", "average", "expensive", "luxury"]


def weighted_choice(weights_dict):
    items, weights = zip(*weights_dict.items())
    return random.choices(items, weights=weights, k=1)[0]


def random_house():
    archetype = weighted_choice(ARCHETYPE_WEIGHTS)
    dists = ARCHETYPES[archetype]
    return {k: weighted_choice(dists[k]) for k in KEYS}


def house_price(house):
    """Sum the weights, add some interaction bonuses + noise."""
    p = PRICE_BASE
    for k, v in house.items():
        p += PRICE_WEIGHTS[k][v]
    # A couple of interactions to make the task richer
    if house["neighborhood"] == "beach" and house["pool"] == "haspool":
        p += 80
    if house["age"] == "vintage" and house["condition"] == "poorcond":
        p -= 60
    if house["size"] == "huge" and house["bedrooms"] == "5+bed":
        p += 60
    p += random.gauss(0, 30)
    return max(0, p)


def price_to_class(price):
    if price < 250:   return 0
    if price < 450:   return 1
    if price < 700:   return 2
    if price < 1000:  return 3
    return 4


def encode_house(house):
    ids = []
    for k in KEYS:
        ids.append(tok2id[k])
        ids.append(tok2id[house[k]])
    return ids


N_HOUSES = 8000

# ----- Show some sample houses BEFORE we train anything -----
# Look at the columns: notice how attributes within an archetype cluster
# together. This is the "correlation structure" pre-training will learn.
print("=" * 70)
print("STEP 1 — Look at the data. Three sample houses, side by side.")
print("=" * 70)
sample_arch = ["rural_cottage", "suburban_family", "luxury_beach"]
samples = []
for arch in sample_arch:
    dists = ARCHETYPES[arch]
    h = {k: weighted_choice(dists[k]) for k in KEYS}
    p = house_price(h)
    samples.append((arch, h, p, price_to_class(p)))

header = f"  {'attribute':<14s}" + "".join(f"{a[0]:>16s}" for a in samples)
print(header)
print("  " + "-" * (14 + 16 * len(samples)))
for k in KEYS:
    row = f"  {k:<14s}" + "".join(f"{a[1][k]:>16s}" for a in samples)
    print(row)
print(f"  {'PRICE ($k)':<14s}" + "".join(f"{a[2]:>16.0f}" for a in samples))
print(f"  {'CLASS':<14s}" + "".join(f"{PRICE_CLASSES[a[3]]:>16s}" for a in samples))
print()
print("  See the patterns? Luxury beach: BIG everywhere. Rural cottage: SMALL.")
print("  Attributes within a house tend to AGREE. That's correlation —")
print("  exactly what pre-training (the fill-in-the-blank game) will learn.\n")

# ----- Now generate the full dataset -----
print(f"Generating {N_HOUSES} synthetic houses with realistic correlations...")
houses, classes = [], []
for _ in range(N_HOUSES):
    h = random_house()
    p = house_price(h)
    houses.append(h)
    classes.append(price_to_class(p))

X = torch.tensor([encode_house(h) for h in houses], dtype=torch.long)
y = torch.tensor(classes, dtype=torch.long)
seq_len = X.size(1)
print(f"  shape X: {tuple(X.shape)}  ({seq_len} tokens per house: 10 keys × 2)")

class_counts = [int((y == c).sum()) for c in range(5)]
print(f"  class spread: bargain={class_counts[0]}, cheap={class_counts[1]}, "
      f"average={class_counts[2]}, expensive={class_counts[3]}, luxury={class_counts[4]}")
print(f"  vocab size: {V}\n")

# ----- Show 10 sample rows from the actual dataset -----
# This is the visceral "what does the dataset look like" view.
# Same 10 rows shown two ways: as pre-training sees them (features only),
# and as the downstream task sees them (features + price label).

# Short abbreviations for values that are too long to fit in 9-char columns
SHORT = {
    "smallgarden": "smGarden", "largegarden": "lgGarden",
    "poorschool":  "poorSch",  "avgschool":   "avgSch",
    "goodschool":  "goodSch",  "excschool":   "excSch",
}
def s(v):
    return SHORT.get(v, v)

CW = 9   # column width
SAMPLE_N = 10

def print_data_table(houses_subset, classes_subset, show_label):
    """Print houses as a wide table. If show_label, append the price class."""
    cols = KEYS
    header = "  row | " + " ".join(f"{c[:CW]:<{CW}}" for c in cols)
    if show_label:
        header += " | price class"
    print(header)
    print("  " + "-" * (len(header) - 2))
    for i in range(SAMPLE_N):
        h = houses_subset[i]
        row = f"  {i+1:>3} | " + " ".join(f"{s(h[k])[:CW]:<{CW}}" for k in cols)
        if show_label:
            row += f" | {PRICE_CLASSES[classes_subset[i]]}"
        print(row)

print("=" * 100)
print("STEP 2 — A wider view: 10 sample rows from the full 8,000-house dataset")
print("=" * 100)
print()
print("(a) As PRE-TRAINING sees them — features only, NO price labels needed:")
print()
print_data_table(houses, classes, show_label=False)
print()
print("    ↑ Pre-training plays fill-in-the-blank on these features alone.")
print("    ↑ Uses ALL 8,000 houses. Labels not needed.")
print()
print("-" * 100)
print()
print("(b) As the DOWNSTREAM TASK sees them — features + price class:")
print()
print_data_table(houses, classes, show_label=True)
print()
print("    ↑ Downstream task uses the full row, INCLUDING the price class.")
print("    ↑ Uses only a small subset of houses (50, 100, 500, or 4000).")
print()

# ----- Show what one house looks like to the computer -----
print("=" * 100)
print("STEP 3 — How the computer sees a single house (plain key-value token IDs)")
print("=" * 100)
first_arch, first_h, _, _ = samples[0]
print(f"  Sample house: {first_arch}")
print(f"  Dict form:    {first_h}")
print(f"  Token IDs:    {encode_house(first_h)}")
print(f"  Tokens:       {[vocab[i] for i in encode_house(first_h)]}\n")
print("  The model never sees 'rural cottage'. Just this 20-element list.\n")


# ============================================================================
# PART 2 — Architecture (same shape as pragma_mini.py)
# ============================================================================

D_MODEL  = 32
N_HEADS  = 2
N_LAYERS = 2


class Encoder(nn.Module):
    def __init__(self, V, d=D_MODEL, heads=N_HEADS, layers=N_LAYERS, max_len=64):
        super().__init__()
        self.emb = nn.Embedding(V, d)
        self.pos = nn.Embedding(max_len, d)
        layer    = nn.TransformerEncoderLayer(d, heads, d * 2, batch_first=True)
        self.enc = nn.TransformerEncoder(layer, layers)
    def forward(self, x):
        positions = torch.arange(x.size(1), device=x.device)
        return self.enc(self.emb(x) + self.pos(positions))


class MLMHead(nn.Module):
    def __init__(self, V, d=D_MODEL):
        super().__init__()
        self.proj = nn.Linear(d, V)
    def forward(self, h):
        return self.proj(h)


class PriceHead(nn.Module):
    def __init__(self, d=D_MODEL, n_classes=5):
        super().__init__()
        self.proj = nn.Linear(d, n_classes)
    def forward(self, h):
        pooled = h.mean(dim=1)
        return self.proj(pooled)


# ============================================================================
# PART 3 — Pre-train via MLM
# ============================================================================
# Higher mask rate (30%) so the model has to genuinely use context from
# remaining tokens to predict masked ones — that's what forces it to learn
# the inter-attribute correlations.

KEY_IDS = torch.tensor([tok2id[k] for k in KEYS])


def mlm_mask(X_batch, p=0.30):
    X = X_batch.clone()
    y = torch.full_like(X, -100)
    is_value = ~torch.isin(X, KEY_IDS)
    pick = (torch.rand_like(X, dtype=torch.float) < p) & is_value
    y[pick] = X[pick]
    X[pick] = tok2id[MASK]
    return X, y


encoder   = Encoder(V)
mlm_head  = MLMHead(V)
opt       = torch.optim.AdamW(list(encoder.parameters()) + list(mlm_head.parameters()), lr=3e-3)
loss_fn   = nn.CrossEntropyLoss(ignore_index=-100)

total_knobs = sum(p.numel() for p in list(encoder.parameters()) + list(mlm_head.parameters()))
print(f"Pre-training encoder via MLM ({total_knobs:,} knobs, 3000 steps)...")
for step in range(3000):
    idx       = torch.randint(0, N_HOUSES, (128,))
    xb, yb    = mlm_mask(X[idx])
    h         = encoder(xb)
    logits    = mlm_head(h)
    loss      = loss_fn(logits.reshape(-1, V), yb.reshape(-1))
    opt.zero_grad(); loss.backward(); opt.step()
    if step % 500 == 0:
        print(f"  step {step:4d}   MLM loss {loss.item():.3f}")

pretrained_encoder = copy.deepcopy(encoder)
print()


# ============================================================================
# PART 4 — Downstream task: predict price class
# ============================================================================

perm  = torch.randperm(N_HOUSES)
split = int(N_HOUSES * 0.8)
tr_idx, te_idx = perm[:split], perm[split:]
X_te, y_te     = X[te_idx], y[te_idx]
print(f"Test set: {len(te_idx)} houses\n")


def freeze(mod):
    for p in mod.parameters(): p.requires_grad = False
    mod.eval()


def train_classifier(encoder, X_tr, y_tr, epochs=500, freeze_encoder=True, batch_size=128):
    head = PriceHead()
    if freeze_encoder:
        freeze(encoder)
        params = list(head.parameters())
    else:
        params = list(encoder.parameters()) + list(head.parameters())
    opt = torch.optim.AdamW(params, lr=3e-3)
    loss_fn = nn.CrossEntropyLoss()

    n = X_tr.size(0)
    for _ in range(epochs):
        if n > batch_size:
            idx = torch.randperm(n)[:batch_size]
            xb, yb = X_tr[idx], y_tr[idx]
        else:
            xb, yb = X_tr, y_tr
        h      = encoder(xb)
        logits = head(h)
        loss   = loss_fn(logits, yb)
        opt.zero_grad(); loss.backward(); opt.step()

    head.eval()
    with torch.no_grad():
        logits = head(encoder(X_te))
        pred   = logits.argmax(-1)
        acc    = (pred == y_te).float().mean().item()
        per_class = []
        for c in range(5):
            mask = (y_te == c)
            if mask.sum() == 0:
                per_class.append(float("nan"))
            else:
                per_class.append((pred[mask] == c).float().mean().item())
        valid = [r for r in per_class if r == r]
        macro_recall = sum(valid) / len(valid) if valid else float("nan")
    return acc, macro_recall, head


print("=" * 70)
print("STEP 7 — The big experiment: PRE-TRAINING recipe vs BASELINE recipe")
print("=" * 70)
print("  PRE-TRAINING recipe: encoder was pre-trained via MLM, then FROZEN.")
print("                       We train ONLY the price head on N labelled houses.")
print()
print("  BASELINE recipe:     random-init encoder, no pre-training.")
print("                       We train the ENTIRE model (encoder + head) end-to-end")
print("                       on the same N labelled houses.")
print()
print("  Both recipes use the same architecture and the same labelled data.")
print("  The ONLY difference is whether we did the pre-training step first.\n")

print(f"{'labels':>7} | {'pretrained acc':>14}  {'pretrained recall':>17} | "
      f"{'baseline acc':>12}  {'baseline recall':>15}")
print("-" * 84)
for n_labels in [50, 100, 500, 4000]:
    sub = tr_idx[:n_labels]
    X_tr, y_tr = X[sub], y[sub]

    # A. Frozen pre-trained encoder + classifier head
    enc_a = copy.deepcopy(pretrained_encoder)
    acc_a, rec_a, _ = train_classifier(enc_a, X_tr, y_tr, freeze_encoder=True)

    # B. Random-init encoder, trained end-to-end
    torch.manual_seed(n_labels)
    enc_b = Encoder(V)
    acc_b, rec_b, _ = train_classifier(enc_b, X_tr, y_tr, freeze_encoder=False)

    print(f"{n_labels:>7} | {acc_a:>14.3f}  {rec_a:>17.3f} | {acc_b:>12.3f}  {rec_b:>15.3f}")

print()


# ============================================================================
# PART 5 — Demo predictions
# ============================================================================

enc_final = copy.deepcopy(pretrained_encoder)
freeze(enc_final)
_, _, head_final = train_classifier(enc_final, X[tr_idx], y[tr_idx], epochs=1000, freeze_encoder=True)

demo_houses = [
    ("rural cottage", {
        "bedrooms": "2bed", "bathrooms": "1bath", "size": "small",  "age": "vintage",
        "neighborhood": "rural", "garage": "1car", "pool": "nopool", "garden": "largegarden",
        "schools": "avgschool", "condition": "faircond"}),
    ("suburban family", {
        "bedrooms": "3bed", "bathrooms": "2bath", "size": "medium", "age": "modern",
        "neighborhood": "suburb", "garage": "2car", "pool": "nopool", "garden": "smallgarden",
        "schools": "goodschool", "condition": "goodcond"}),
    ("luxury beach", {
        "bedrooms": "5+bed", "bathrooms": "3+bath", "size": "huge", "age": "new",
        "neighborhood": "beach", "garage": "2car", "pool": "haspool", "garden": "largegarden",
        "schools": "excschool", "condition": "exccond"}),
]
print("Sample predictions:")
for label, h in demo_houses:
    ids = torch.tensor([encode_house(h)])
    with torch.no_grad():
        logits = head_final(enc_final(ids))
        probs  = torch.softmax(logits, dim=-1)[0].tolist()
        pred   = logits.argmax(-1).item()
    bars = "  ".join(f"{PRICE_CLASSES[c]:>10s}={probs[c]*100:5.1f}%" for c in range(5))
    print(f"\n  {label:18s}  prediction: {PRICE_CLASSES[pred]}")
    print(f"  {bars}")
